[package]
name = "amethyst-tanks-rs"
version = "0.1.0"
authors = ["AlexNav73 <fifthhorseman@mail.ru>"]
edition = "2018"

[dependencies]
pathfinding = "1.1.12"

[dependencies.amethyst]
version = "0.10.0"
features = ["nightly"]
